# Generated by Django 4.0.3 on 2022-04-07 15:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('h_apps', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Contact',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, null=True)),
                ('email', models.EmailField(max_length=100, null=True)),
                ('message', models.TextField(max_length=500, null=True)),
                ('subject', models.TextField(max_length=500, null=True)),
                ('country', models.TextField(max_length=500, null=True)),
            ],
        ),
        migrations.DeleteModel(
            name='login',
        ),
    ]
